import { fetchAllProducts, fetchCategories } from "@/apiCalls/apiCalls";
import Banner from "@/components/Home/Banner";
import Categories from "@/components/Home/Categories";
import ProductWrapper from "@/components/Home/ProductWrapper";
import Layout from "@/layout/Layout";
import { setCategories } from "@/redux/categoriesSlice";
import { setProducts } from "@/redux/productSlice";
import Head from "next/head";
import { useEffect } from "react";
import { useDispatch } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();

  useEffect(() => {
    getCategories();
    getAllProducts();
  }, []);

  const getCategories = async () => {
    const categories = await fetchCategories();
    dispatch(setCategories(categories));
  };

  const getAllProducts = async () => {
    const allProducts = await fetchAllProducts();
    dispatch(setProducts(allProducts));
  };

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Banner />
        <div className="flex w-[96%] mx-auto my-1">
          <Categories />
          <ProductWrapper />
        </div>
      </div>
    </Layout>
  );
}
